### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Xuxiaoxiaohaha** [Yong-DAI/PC#1]
请问本仓库代码是能正常运行的吗？我发现vision_transformer.py中注释存在问题，以及在运行训练脚本时报错：  File "/home/xxxx/miniconda3/envs/pc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 316, in add_param_group
    raise ValueError("some parameters appear in more than one parameter group")

**Comment by Xuxiaoxiaohaha** [comment]
> 请问本仓库代码是能正常运行的吗？我发现vision_transformer.py中注释存在问题，以及在运行训练脚本时报错： File "/home/xxxx/miniconda3/envs/pc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 316, in add_param_group raise ValueError("some parameters appear in more than one parameter group")

通过如下方式修复：
```
    base_params = []
    maben_para = []
    for n,p in model_without_ddp.named_parameters():
        if n.startswith('e_prompt.maben'):
            maben_para.append(p)
        else:
            base_params.append(p)
```

**Comment by Yong-DAI** [comment]
您好，感谢关注我们的工作。代码没有问题，应该可以直接运行主函数。不过因为环境配置版本不同，也可能需要微调一下代码。












--


---Original---
From: ***@***.***&gt;
Sent at: 2024年9月15日(Sun) Evening8:46
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Yong-DAI/PC] 代码问题 (Issue #1)




  
请问本仓库代码是能正常运行的吗？我发现vision_transformer.py中注释存在问题，以及在运行训练脚本时报错： File "/home/xxxx/miniconda3/envs/pc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 316, in add_param_group raise ValueError("some parameters appear in more than one parameter group")
  
通过如下方式修复：
     base_params = [] maben_para = [] for n,p in model_without_ddp.named_parameters(): if n.startswith('e_prompt.maben'): maben_para.append(p) else: base_params.append(p)
